name: Update GitHub Stats

on:
  push:
    branches:
      - '**'         # run on any push to any branch
  pull_request:
    branches:
      - '**'         # also run on PRs
  schedule:
    - cron: '0 5 * * *' # every day at 05:00 UTC (midnight ET)
  workflow_dispatch:      # manual trigger
  repository_dispatch:    # trigger via API/CLI
    types: [update-stats]

permissions:
  contents: write

jobs:
  update-stats:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: python -m pip install --upgrade pip requests

      - name: Generate GitHub stats and update README
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_OWNER: sbidwaibing   # update if your username is different
          README_PATH: README.md
        run: |
          python .github/scripts/generate_github_stats.py

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "chore: update GitHub stats"
            git pull --rebase origin main   # ✅ fix push rejected issue
            git push origin main
          fi
